name: CI Pipeline   # workflow name

on:
  push:
    branches: [ "main" ]   # trigger when we push to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest   # runner (like a virtual Linux machine)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x monitor.sh

      - name: Run monitor script
        run: ./monitor.sh
