name: CI pipeline
on: 
 push:
   branches: [ "main" ]
jobs: 
  build:
    runs-on: ubuntu-latest
steps:
  -name: checkout code
  uses: actions/checkout@v3
  -name: make script executable
  run: chmod+x monitor.sh
  -name: run monitor script
  run: ./monitor.sh
