name: CI Pipeline   # workflow name

on:
  push:
    branches: [ "main" ]   # trigger when we push to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest   # runner (like a virtual Linux machine)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x monitor.sh

      - name: Run monitor script
        run: ./monitor.sh
      - name: Fake tests
        run: |
          echo "Running tests..."
          if [ -f monitor.sh ]; then
          echo "Test passed: Script exists"
      - name: Package artifact
        run: |
          mkdir -p artifacts
          cp monitor.sh artifacts/
          echo "Packaged script into artifacts/"

      - name: Deploy stage (simulate)
        run: |
          mkdir -p deploy
          cp artifacts/monitor.sh deploy/
          echo "Deployed script to deploy/ folder"
          else
            echo "Test failed: Script missing" && exit 1
          fi
